// T014: tokens-emitter.cjs — write merged tokens to <deck>/src/deck/tokens.ts.
//
// Preserves the THEME shape from scaffold-template/src/deck/tokens.ts and
// emits a comment ABOVE each field documenting the contributing layer:
//   // background: from theme=stacklink-dark
//
// Static parts (radius/shadow/spacing scales, connectorPalette) are kept as
// the scaffold defaults unless tokens supplies overrides.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const FONT_FIELDS = new Set(['fontDisplay', 'fontBody', 'fontMono']);

const DEFAULT_RADIUS = { sm: '0.25rem', md: '0.5rem', lg: '0.75rem', xl: '1rem' };
const DEFAULT_SHADOW = {
  sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"
};
const DEFAULT_SPACING = {
  0: '0rem', 1: '0.25rem', 2: '0.5rem', 3: '0.75rem', 4: '1rem',
  5: '1.25rem', 6: '1.5rem', 8: '2rem', 10: '2.5rem', 12: '3rem',
  16: '4rem', 20: '5rem', 24: '6rem', 32: '8rem'
};
const DEFAULT_CONNECTORS = {
  drive: '#4285F4', slack: '#ECB22E', github: '#C9D1D9', notion: '#FFFFFF',
  onedrive: '#28A8EA', salesforce: '#00A1E0', jira: '#0052CC',
  confluence: '#172B4D', teams: '#5059C9', linear: '#5E6AD2'
};

const COLOR_FIELDS = [
  'background', 'foreground', 'mutedForeground', 'border',
  'surfaceBase', 'surfaceSubtle', 'surfaceRaised',
  'success', 'info', 'warning', 'destructive'
];

function fmtVal(v) {
  // Font strings often contain double quotes; emit as single-quoted JS.
  if (typeof v === 'string' && v.includes("'")) return JSON.stringify(v);
  return `'${v}'`;
}

function commentFor(field, sources, themeName) {
  const layer = sources[field] || 'default';
  const detail = layer === 'theme' ? `theme=${themeName}` : layer;
  return `  // ${field}: from ${detail}`;
}

function emitTokensFile({ tokens, sources, themeName = 'stacklink-dark', deckPath }) {
  const targetDir = path.join(deckPath, 'src', 'deck');
  fs.mkdirSync(targetDir, { recursive: true });
  const target = path.join(targetDir, 'tokens.ts');

  const lines = [];
  lines.push('// Generated by morph-deck token-merger (T014).');
  lines.push('// Layer attribution per field is preserved as comments below.');
  lines.push('');
  lines.push('export const THEME = {');

  // Color tokens.
  lines.push('  // --- Color tokens (R008.AC1) ---');
  for (const f of COLOR_FIELDS) {
    if (tokens[f] == null) continue;
    lines.push(commentFor(f, sources, themeName));
    lines.push(`  ${f}: ${fmtVal(tokens[f])},`);
  }

  // Font tokens.
  lines.push('  // --- Font tokens (R008.AC2) ---');
  for (const f of ['fontDisplay', 'fontBody', 'fontMono']) {
    if (tokens[f] == null) continue;
    lines.push(commentFor(f, sources, themeName));
    lines.push(`  ${f}: ${fmtVal(tokens[f])},`);
  }

  // Radius / shadow / spacing — use theme overrides if present, else defaults.
  const radius = tokens.radius || DEFAULT_RADIUS;
  const shadow = tokens.shadow || DEFAULT_SHADOW;
  const spacing = tokens.spacing || DEFAULT_SPACING;

  lines.push('  // --- Radius scale (R008.AC3) ---');
  lines.push(`  radiusSm: ${fmtVal(radius.sm)},`);
  lines.push(`  radiusMd: ${fmtVal(radius.md)},`);
  lines.push(`  radiusLg: ${fmtVal(radius.lg)},`);
  lines.push(`  radiusXl: ${fmtVal(radius.xl)},`);

  lines.push('  // --- Shadow tokens (R008.AC3) ---');
  lines.push(`  shadowSm: ${fmtVal(shadow.sm)},`);
  lines.push(`  shadowMd: ${fmtVal(shadow.md)},`);
  lines.push(`  shadowLg: ${fmtVal(shadow.lg)},`);

  lines.push('  // --- Spacing scale (R008.AC3) ---');
  lines.push('  spacing: {');
  for (const k of Object.keys(spacing)) {
    lines.push(`    ${k}: ${fmtVal(spacing[k])},`);
  }
  lines.push('  },');

  // Connector palette.
  const connectors = tokens.connectorPalette || DEFAULT_CONNECTORS;
  lines.push('  // --- Connector palette (R008.AC6) ---');
  lines.push('  connectorPalette: {');
  for (const k of Object.keys(connectors)) {
    lines.push(`    ${k}: ${fmtVal(connectors[k])},`);
  }
  lines.push('  }');

  lines.push('} as const;');
  lines.push('');
  lines.push('export type Theme = typeof THEME;');
  lines.push('');

  fs.writeFileSync(target, lines.join('\n'), 'utf8');
  return target;
}

module.exports = { emitTokensFile };
